nama = input("Masukkan nama anda: ")
nama_panggilan = input("Masukkan nama panggilan anda: ")
umur = int(input("Masukkan umur anda: "))
mahasiswa = bool(input("Apakah anda seorang mahasiswa? (true/false): "))
universitas = input("Masukkan nama universitas anda: ")
nim = int(input("Masukkan NIM anda: "))
fakultas = input("Masukkan fakultas anda: ")
prodi = input("Masukkan prodi anda: ")
tinggi_badan = float(input("Masukkan tinggi badan anda: "))
berat_badan = float(input("Masukkan berat badan anda: "))

print("\n Biodata diri anda:")
print("Nama:", nama)
print("Nama panggilan:", nama_panggilan)
print("Umur:", umur, "tahun")
print("Mahasiswa:", mahasiswa)
print("Universitas:", "Universitas", universitas)
print("NIM:", nim)
print("Fakultas:", fakultas)
print("Prodi:", prodi)
print("Tinggi badan:", tinggi_badan, "cm")
print("Berat badan:", berat_badan, "kg")